---
title: "Introducing the 'polmineR.graph'-package"
author: "Andreas Blätte (andreas.blaette@uni-due.de)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to polmineR.graph}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---


```{r, eval = TRUE, message = FALSE, echo = FALSE}
runcode <- FALSE
if ("CORPUS_REGISTRY" %in% names(Sys.getenv()) && nchar(Sys.getenv("CORPUS_REGISTRY")) > 1){
  library(data.table)
  if (require("rcqp", quietly = T) && require("plprbt.pvs2017", quietly = T)) runcode <- TRUE
}
```
 

Analysing ego networks: Using cooccurrences-method
--------------------------------------------------

Analysing cooccurrence networks does not necessarily require the \code{polmineR.graph} package.
In a first example, I show how to use the \code{cooccurrences}-method and the \code{cooccurrencesBundle}-
class to get the ego-network of a term. Here, I will analyse the cooccurrences of a query ("Islam") without
using CQP syntax, but using the CQP syntax would be possible.

```{r}
query <- "Islam"
use.cqp <- FALSE
```

I will use the corpus called "PLPRBT" in the \code{plprbt.pvs2017}-package. As this might be particularly
interesting, I generate a partition for 2002 that will serve as the corpus of interest (coi), assuming that
it may be particularly interesting to gain an insight into that associations Islam evoqued in the year after 
September 11.

```{r}
library(polmineR)
use("plprbt.pvs2017")
coi <- partition("PLPRBT", text_year = as.character(2002), pAttribute = c("word", "pos"))
coi <- Corpus$new("PLPRBT", pAttribute = c("word", "pos"))
```

At this stage, let us define a few general parameters for the analysis. We are not interested in substantive
associations rather than linguistic features, so the left and right context should be sufficiently large
(10 words in this case). Working with cooccurrences usually requires filtering. For that, we use the
part-of-speech annotation of the corpus, and we drop kinds of words without substantive meaning. Finally,
if a term occurrs less than three times, and the statistical test remains below the 10.83-threshold,
we do not include it in the further analysis. 

```{r}
options("polmineR.left" = 10)
options("polmineR.right" = 10)
pAttrs <- c("word", "pos")
posToDrop <- c(
  "ART", "APPR", "PRELS", "PDAT", "$(", "$.", "$,", "APPRAR",
  "VAFIN", "APPRART", "KOUI", "KON", "PPOSAT", "KOUS"
  )
min.count <- 3
min.ll <- 10.83
max.coocs <- 10
```

With these options set, let us get the cooccurrences for the query first ...

```{r}
nodeCoocs <- cooccurrences(coi, query = query, cqp = use.cqp, pAttribute = pAttrs, verbose = FALSE)
```

Then we do the filtering, using the parameters defined before. For that purpose, we can use the 
subset-method that is applied to the \code{data.table} in the slot "stat" if the cooccurrences object.

```{r}
nodeCoocsMin <- subset(nodeCoocs, !pos %in% posToDrop)
nodeCoocsMin <- subset(nodeCoocsMin, count_window >= min.count)
nodeCoocsMin <- subset(nodeCoocsMin, ll >= min.ll)
if (nrow(nodeCoocsMin) > max.coocs) nodeCoocsMin <- nodeCoocsMin[1:max.coocs]
```

In the column "word" of the \code{data.table} in the cooccurrences-object, we find the statistically
significant cooccurrences of the query ("Islam"). Using pblapply to get a list, we iterate through these words,
using these words as queries. In that process, the same filtering as before is applied. Note: pblapply is 
essentially the same as lapply, but shows a nice progress bar.

```{r}
library(pbapply)
coocs <- pbapply::pblapply(
  nodeCoocsMin[["word"]],
  function(token){
    C <- cooccurrences(coi, query = token, cqp = FALSE, pAttribute = pAttrs, verbose = FALSE)
    C <- subset(C, !pos %in% posToDrop)
    C <- subset(C, count_window >= min.count)
    C <- subset(C, ll >= min.ll)
    if (nrow(C) > max.coocs) C <- C[1:max.coocs]
    C
  }
)
```

To procceed to an object that can be processed by some graph visualisation engine, the trick 
is now to bundle the cooccurrence analysis for the node and its cooccurrences in a cooccurrencesBundle
object.

```{r}
coocBundle <- new("cooccurrencesBundle", objects = coocs)
coocBundle <- coocBundle + nodeCoocsMin
```

That can be turned into a data.frame easily. 

```{r}
df <- as.data.frame(coocBundle)
df[["b"]] <- gsub("^(.*?)//.*?$", "\\1", df[["b"]])
```

We now have everything we need for using igraph. We turn our data.frame into an igraph object,
and add communities and coordinates using two auxiliary functions included in the polmineR.graph
package. 

```{r}
library(igraph)
library(polmineR.graph)
G <- igraph::graph_from_data_frame(df)
G <- simplify(
  G, remove.multiple = TRUE, remove.loops = TRUE,
  edge.attr.com = list(weight = "mean", name = "concat")
  )
G <- addCommunities(G, method = "fastgreedy", weights = FALSE)
G <- addCoordinates(G, layout = "kamada.kawai", dim = 3)
```

This is an object that can be plotted. Of course, a lot of further beauty can be added using the 
various parameters of the igraph library. Explaining this goes beyond this tutorial.

```{r}
plot(G)
```

The polmineR.graph package includes a class that can produce a SVG graphic ...

```{r}
S <- SVG(G)
S$width <- 500
S$height <- 500
S$fontSize <- 12
S$make()
S$browse()
```

You can export the graph to Gephi ...

```{r}
library(rgexf)
gephi <- rgexf::igraph.to.gexf(G)
print(gephi, file = "~/Lab/tmp/gephi.gexf")
```

You can use an advanced visualisation tool such as D3 ...

```{r}
library(networkD3)
links <- as.data.frame(cbind(
  as_edgelist(G, names = FALSE),
  sapply(E(G)$ll, function(x) x[1])
  ))
links[,1] <- links[,1] - 1
links[,2] <- links[,2] - 1 
colnames(links) <- c("source", "target", "value")
nodes <- data.frame(
  name = V(G)$name,
  group = V(G)$community,
  size = 3
)
forceNetwork(
  Links = links, Nodes = nodes, Source = "source",
  Target = "target", Value = "value", NodeID = "name",
  Group = "group", opacity = 0.75, fontSize = 20, zoom = TRUE
  )
```


Analysing ego networks: Using Cooccurrences-class
-------------------------------------------------


# Loading required libraries

```{r}
library(polmineR)
library(data.table)
library(polmineR.graph)
library(igraph)
library(RColorBrewer)
library(three)
```


# Configuration

```{r}
termOfInterest <- "Ungleichheit"
corpus <- "PLPRBT"
sAttr <- "speaker_year" # for PLPRBT, would be "text_year" for many other corpora
pAttr <- "lemma"
use.regex <- TRUE
years <- as.character(1998:2015)
window.size <- 10L

threshold <- 3.84
min.count <- 3
graph.order = 1L


svg.width <- 800
svg.height <- 650
svg.margin <- 100
svg.fontSize <- 13
svg.edgeColor <- "lightgrey"

setwd("~/Lab/tmp/ungleichheit") # output html files will be stored here
```


# helper function

```{r}
makeSVG <- function(sAttrValue, label){
  
  print(year)
  
  # create partition
  defList <- as.list(setNames(sAttrValue, sAttr))
  P <- partition(corpus, def = defList, pAttribute = pAttr, regex = use.regex)

  coocTest <- cooccurrences(P, query = termOfInterest, pAttribute = pAttr)
  if (length(which(coocTest[["count_window"]] >= 5)) <= 5){
    msg <- "less than 5 statistically significant cooccurrences"
    warning(msg, year)
    return(NULL)
  }
  
  # create Cooccurrences object
  termsToDrop <- c(polmineR::punctuation, unlist(noise(pAttributes(P, pAttribute = pAttr))))
  Cooc <- Cooccurrences$new(partition = P, pAttribute = pAttr, window = window.size, drop = termsToDrop)
  Cooc$count()
  Cooc$trim(action = "drop", by.id = TRUE)
  Cooc$maths()
  
  # minimize by applying statistical threshold, reduction to token neighborhood
  CoocMin <- copy(Cooc)
  CoocMin$dt <- copy(Cooc$dt)
  CoocMin$dt <- CoocMin$dt[ll > threshold]
  CoocMin$dt <- CoocMin$dt[count_ab >= min.count]
  G <- CoocMin$as.igraph(as.undirected = TRUE)
  if (! termOfInterest %in% V(G)$name){
    warning("no statistignificantly reliable result for ", year)
    return(NULL)
  }
  Gmin <- make_ego_graph(G, order = graph.order, nodes = termOfInterest)[[1]]
  Gmin <- addCommunities(Gmin)
  Gmin <- addCoordinates(Gmin, layout = "kamada.kawai", dim = 2)
  
  # turn into SVG
  S <- SVG$new(Gmin)
  S$width = svg.width
  S$height = svg.height
  S$margin = svg.margin
  S$fontSize = svg.fontSize
  S$edgeColor = svg.edgeColor
  S$make()
  outfile <- S$store(filename = file.path(getwd(), paste(year, ".html", sep = "")))
  print(outfile)

}
```


# Generate output

```{r}
for (year in years) makeSVG(sAttrValue = year, label = year)
```

```{r}
makeSVG(sAttrValue = as.character(1998:2008), label = "pre2008")
makeSVG(sAttrValue = as.character(2008:2015), label = "2008ff")
```

